# Generated by Django 6.0.8 on 2026-10-07 13:18

from django.db import migrations, models


def _location_column(table):
    """Generated, GiST-indexed `location` geography column (kept out of the models)."""
    return migrations.RunSQL(
        sql=f"""
            ALTER TABLE {table} ADD COLUMN location geography(Point, 4326)
                GENERATED ALWAYS AS (
                    CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL
                        THEN ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
                    END
                ) STORED;
            CREATE INDEX {table}_location_gist ON {table} USING GIST (location);
        """,
        reverse_sql=f"ALTER TABLE {table} DROP COLUMN location;",
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS postgis;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='BirdObservationModel',
            fields=[
                ('observation_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('observed_on', models.DateField(blank=True, db_index=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bird observation',
                'db_table': 'geodata_bird_observation',
            },
        ),
        migrations.CreateModel(
            name='DatacenterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('opened_on', models.DateField(blank=True, db_index=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'datacenter',
                'db_table': 'geodata_datacenter',
            },
        ),
        _location_column('geodata_bird_observation'),
        _location_column('geodata_datacenter'),
    ]
